---
# Spring Setting
spring:
  profiles: default

# Embedded server Setting
server:
  port: 8089

# datasource Setting
datasource:
  oauth:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: test
    password: test
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    minimum-idle: 10 # same initial-size
    maximum-pool-size: 10
    pool-name: oauth-oauth-cp
    max-wait: 1000
    initial-size: 10
    connection-init-sql: /* TEST New Connection Pool Create */ SELECT 1
---
# Spring Setting
spring:
  profiles: development

# datasource Setting
datasource:
  test:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: test
    password: test
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    minimum-idle: 10 # same initial-size
    maximum-pool-size: 10
    pool-name: oauth-oauth-cp
    max-wait: 1000
    initial-size: 10
    connection-init-sql: /* TEST New Connection Pool Create */ SELECT 1